In [5]:
import numpy as np

rows=3
cols=4 
beers=3

#stake out some memory using zeros()
arr=np.zeros([beers, rows, cols], dtype=int)

#add each element
for el in range(beers):
    for r in range(rows):
        for c in range(cols):
            arr[el, r, c]=(el + 1) * 100 + (r + 1) * 10 + (c + 1)

In [23]:
print(f"The entire array:")
arr

The entire array:


array([[[111, 112, 113, 114],
        [121, 122, 123, 124],
        [131, 132, 133, 134]],

       [[211, 212, 213, 214],
        [221, 222, 223, 224],
        [231, 232, 233, 234]],

       [[311, 312, 313, 314],
        [321, 322, 323, 324],
        [331, 332, 333, 334]]])

In [25]:
IPA = arr[0]
print("IPA:")
IPA

IPA:


array([[111, 112, 113, 114],
       [121, 122, 123, 124],
       [131, 132, 133, 134]])

In [24]:
chunk_of_lagers = arr[1, 1:3, 1:3]
print("A chunk of the lagers:")
chunk_of_lagers

A chunk of the lagers:


array([[222, 223],
       [232, 233]])

In [26]:
middle_row_of_stouts = arr[2, 2, :]
print("Middle row of stouts:")
middle_row_of_stouts

Middle row of stouts:


array([331, 332, 333, 334])